"""restart

Revision ID: 7bdb2cfcd09c
Revises: 
Create Date: 2026-02-12 08:13:19.193303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bdb2cfcd09c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_guid'), 'account', ['guid'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_asset', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nm_asset', name='uq_asset')
    )
    op.create_index(op.f('ix_assets_nm_asset'), 'assets', ['nm_asset'], unique=False)
    op.create_table('dominio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_dominio', sa.String(length=32), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index(op.f('ix_dominio_nm_dominio'), 'dominio', ['nm_dominio'], unique=False)
    op.create_table('balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id_asset', sa.Integer(), nullable=False),
    sa.Column('available', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('locked', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_asset'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'id_asset', name='uq_balance_account_id_asset')
    )
    op.create_index(op.f('ix_balance_account_id'), 'balance', ['account_id'], unique=False)
    op.create_index('ix_balance_id_asset', 'balance', ['id_asset'], unique=False)
    op.create_table('balance_hold',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id_asset', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_asset'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['id_status'], ['dominio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_hold_account_id'), 'balance_hold', ['account_id'], unique=False)
    op.create_index('ix_balance_hold_id_asset', 'balance_hold', ['id_asset'], unique=False)
    op.create_index(op.f('ix_balance_hold_id_status'), 'balance_hold', ['id_status'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id_asset', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_asset'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_event_account_id'), 'event', ['account_id'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index('ix_event_id_asset', 'event', ['id_asset'], unique=False)
    op.create_index(op.f('ix_event_reference_id'), 'event', ['reference_id'], unique=False)
    op.create_table('settlement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id_asset', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('from_address', sa.String(length=128), nullable=False),
    sa.Column('to_address', sa.String(length=128), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('blockchain', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_asset'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['id_status'], ['dominio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_account_id'), 'settlement', ['account_id'], unique=False)
    op.create_index(op.f('ix_settlement_blockchain'), 'settlement', ['blockchain'], unique=False)
    op.create_index('ix_settlement_id_asset', 'settlement', ['id_asset'], unique=False)
    op.create_index(op.f('ix_settlement_id_status'), 'settlement', ['id_status'], unique=False)
    op.create_index(op.f('ix_settlement_tx_hash'), 'settlement', ['tx_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_tx_hash'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_id_status'), table_name='settlement')
    op.drop_index('ix_settlement_id_asset', table_name='settlement')
    op.drop_index(op.f('ix_settlement_blockchain'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_account_id'), table_name='settlement')
    op.drop_table('settlement')
    op.drop_index(op.f('ix_event_reference_id'), table_name='event')
    op.drop_index('ix_event_id_asset', table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_account_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_balance_hold_id_status'), table_name='balance_hold')
    op.drop_index('ix_balance_hold_id_asset', table_name='balance_hold')
    op.drop_index(op.f('ix_balance_hold_account_id'), table_name='balance_hold')
    op.drop_table('balance_hold')
    op.drop_index('ix_balance_id_asset', table_name='balance')
    op.drop_index(op.f('ix_balance_account_id'), table_name='balance')
    op.drop_table('balance')
    op.drop_index(op.f('ix_dominio_nm_dominio'), table_name='dominio')
    op.drop_table('dominio')
    op.drop_index(op.f('ix_assets_nm_asset'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_account_guid'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
