"""initial migration

Revision ID: 365333e905e5
Revises: 
Create Date: 2026-02-05 09:13:05.567340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365333e905e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'asset', name='uq_account_account_asset')
    )
    op.create_index(op.f('ix_account_account_id'), 'account', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_asset'), 'account', ['asset'], unique=False)
    op.create_table('settlement_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('settlement_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_status_settlement_id'), 'settlement_status', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_settlement_status_status'), 'settlement_status', ['status'], unique=False)
    op.create_table('balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('available', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('locked', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'asset', name='uq_balance_account_asset')
    )
    op.create_index(op.f('ix_balance_account_id'), 'balance', ['account_id'], unique=False)
    op.create_index(op.f('ix_balance_asset'), 'balance', ['asset'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('delta', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_event_account_id'), 'event', ['account_id'], unique=False)
    op.create_index(op.f('ix_event_asset'), 'event', ['asset'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_reference_id'), 'event', ['reference_id'], unique=False)
    op.create_table('settlement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('from_address', sa.String(length=128), nullable=False),
    sa.Column('to_address', sa.String(length=128), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('blockchain', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_status'], ['settlement_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_account_id'), 'settlement', ['account_id'], unique=False)
    op.create_index(op.f('ix_settlement_asset'), 'settlement', ['asset'], unique=False)
    op.create_index(op.f('ix_settlement_blockchain'), 'settlement', ['blockchain'], unique=False)
    op.create_index(op.f('ix_settlement_id_status'), 'settlement', ['id_status'], unique=False)
    op.create_index(op.f('ix_settlement_tx_hash'), 'settlement', ['tx_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_tx_hash'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_id_status'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_blockchain'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_asset'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_account_id'), table_name='settlement')
    op.drop_table('settlement')
    op.drop_index(op.f('ix_event_reference_id'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_asset'), table_name='event')
    op.drop_index(op.f('ix_event_account_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_balance_asset'), table_name='balance')
    op.drop_index(op.f('ix_balance_account_id'), table_name='balance')
    op.drop_table('balance')
    op.drop_index(op.f('ix_settlement_status_status'), table_name='settlement_status')
    op.drop_index(op.f('ix_settlement_status_settlement_id'), table_name='settlement_status')
    op.drop_table('settlement_status')
    op.drop_index(op.f('ix_account_asset'), table_name='account')
    op.drop_index(op.f('ix_account_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
