"""init ledger

Revision ID: 9cb4aa2d24b4
Revises: 
Create Date: 2026-01-29 07:35:07.489363

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cb4aa2d24b4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_balance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(length=80), nullable=False),
        sa.Column("asset", sa.String(length=16), nullable=False),
        sa.Column("available", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("locked", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "asset", name="uq_balance_account_asset"),
    )
    op.create_index(op.f("ix_ledger_balance_account_id"), "ledger_balance", ["account_id"], unique=False)
    op.create_index(op.f("ix_ledger_balance_asset"), "ledger_balance", ["asset"], unique=False)
    op.create_table(
        "ledger_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("account_id", sa.String(length=80), nullable=False),
        sa.Column("asset", sa.String(length=16), nullable=False),
        sa.Column("delta", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("reference_type", sa.String(length=32), nullable=False),
        sa.Column("reference_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_ledger_event_account_id"), "ledger_event", ["account_id"], unique=False)
    op.create_index(op.f("ix_ledger_event_asset"), "ledger_event", ["asset"], unique=False)
    op.create_index(op.f("ix_ledger_event_event_type"), "ledger_event", ["event_type"], unique=False)
    op.create_index(op.f("ix_ledger_event_reference_id"), "ledger_event", ["reference_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ledger_event_reference_id"), table_name="ledger_event")
    op.drop_index(op.f("ix_ledger_event_event_type"), table_name="ledger_event")
    op.drop_index(op.f("ix_ledger_event_asset"), table_name="ledger_event")
    op.drop_index(op.f("ix_ledger_event_account_id"), table_name="ledger_event")
    op.drop_table("ledger_event")
    op.drop_index(op.f("ix_ledger_balance_asset"), table_name="ledger_balance")
    op.drop_index(op.f("ix_ledger_balance_account_id"), table_name="ledger_balance")
    op.drop_table("ledger_balance")
    # ### end Alembic commands ###
