"""fixes

Revision ID: a87b5d59913a
Revises: 365333e905e5
Create Date: 2026-02-05 09:20:47.540538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87b5d59913a'
down_revision: Union[str, None] = '365333e905e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('guid', sa.String(length=80), nullable=False))
    op.drop_index('ix_account_account_id', table_name='account')
    op.drop_constraint('uq_account_account_asset', 'account', type_='unique')
    op.create_index(op.f('ix_account_guid'), 'account', ['guid'], unique=True)
    op.drop_column('account', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_account_guid'), table_name='account')
    op.create_unique_constraint('uq_account_account_asset', 'account', ['account_id', 'asset'])
    op.create_index('ix_account_account_id', 'account', ['account_id'], unique=False)
    op.drop_column('account', 'guid')
    # ### end Alembic commands ###
