"""fixes2

Revision ID: 389de009d60e
Revises: a87b5d59913a
Create Date: 2026-02-05 09:25:36.566191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389de009d60e'
down_revision: Union[str, None] = 'a87b5d59913a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_asset', table_name='account')
    op.drop_column('account', 'asset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('asset', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.create_index('ix_account_asset', 'account', ['asset'], unique=False)
    # ### end Alembic commands ###
